name: IListEffectDemo
options:
  bundleIdPrefix: com.ibabyblue
  deploymentTarget:
    iOS: "17.0"
packages:
  IListEffect:
    path: ..
targets:
  IListEffectDemo:
    type: application
    platform: iOS
    sources: [IListEffectDemo]
    dependencies:
      - package: IListEffect
        product: ListEffect-UIKit
      - package: IListEffect
        product: ListEffect-SwiftUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ibabyblue.IListEffectDemo
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.10"
  IListEffectDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources: [IListEffectDemoTests]
    dependencies:
      - target: IListEffectDemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ibabyblue.IListEffectDemoTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.10"
schemes:
  IListEffectDemo:
    build:
      targets:
        IListEffectDemo: all
    test:
      targets:
        - name: IListEffectDemoTests
          parallelizable: false
